=== danteay/CorePHP/setup/themes/NewDefault/themedtd.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT components (directives,general,views)>

<!ELEMENT directives (name,findfolder,makedirs)>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT findfolder (#PCDATA)>
    <!ELEMENT makedirs (dir*)>

        <!ELEMENT dir (#PCDATA)>

<!ELEMENT general (navigation, footer?, plugins?)>

    <!ELEMENT navigation EMPTY>
    <!ATTLIST navigation structure CDATA #REQUIRED>

    <!ELEMENT footer EMPTY>
    <!ATTLIST footer structure CDATA #REQUIRED>

    <!ELEMENT plugins (dateplugin?,timeplugin?,datetimeplugin?,validateplugin?)>

        <!ELEMENT dateplugin (activation?)>
        <!ATTLIST dateplugin css CDATA #REQUIRED>
        <!ATTLIST dateplugin js CDATA #REQUIRED>

        <!ELEMENT timeplugin (activation?)>
        <!ATTLIST timeplugin css CDATA #REQUIRED>
        <!ATTLIST timeplugin js CDATA #REQUIRED>

        <!ELEMENT datetimeplugin (activation?)>
        <!ATTLIST datetimeplugin css CDATA #REQUIRED>
        <!ATTLIST datetimeplugin js CDATA #REQUIRED>

            <!ELEMENT validateplugin (addmodal,editmodal,activation?)>
            <!ATTLIST validateplugin css CDATA #REQUIRED>
            <!ATTLIST validateplugin js CDATA #REQUIRED>
            <!ATTLIST validateplugin structure CDATA #REQUIRED>

                <!ELEMENT addmodal EMPTY>
                <!ATTLIST addmodal js CDATA #REQUIRED>
                <!ATTLIST addmodal folder CDATA #REQUIRED>
                <!ATTLIST addmodal validate CDATA #REQUIRED>

                <!ELEMENT editmodal EMPTY>
                <!ATTLIST editmodal js CDATA #REQUIRED>
                <!ATTLIST editmodal folder CDATA #REQUIRED>
                <!ATTLIST editmodal validate CDATA #REQUIRED>

            <!ELEMENT activation EMPTY>
            <!ATTLIST activation actcode CDATA #REQUIRED>

<!ELEMENT views (indexview,homeview,reportview,addview,editview)>

    <!ELEMENT indexview EMPTY>
    <!ATTLIST indexview structure CDATA #REQUIRED>

    <!ELEMENT homeview (listNavigation)>
    <!ATTLIST homeview structure CDATA #REQUIRED>

        <!ELEMENT listNavigation EMPTY>
        <!ATTLIST listNavigation structure CDATA #REQUIRED>

    <!ELEMENT reportview (editbutton)>
    <!ATTLIST reportview structure CDATA #REQUIRED>

        <!ELEMENT editbutton EMPTY>
        <!ATTLIST editbutton structure CDATA #REQUIRED>
        <!ATTLIST editbutton header CDATA #REQUIRED>

    <!ELEMENT addview (adddateinput,addtimeinput,addtextarea,adddefaultinput,adddatetimeinput)>
    <!ATTLIST addview structure CDATA #REQUIRED>

        <!ELEMENT adddateinput EMPTY>
        <!ATTLIST adddateinput structure CDATA #REQUIRED>

        <!ELEMENT addtimeinput EMPTY>
        <!ATTLIST addtimeinput structure CDATA #REQUIRED>

        <!ELEMENT addtextarea EMPTY>
        <!ATTLIST addtextarea structure CDATA #REQUIRED>

        <!ELEMENT adddefaultinput EMPTY>
        <!ATTLIST adddefaultinput structure CDATA #REQUIRED>

        <!ELEMENT adddatetimeinput EMPTY>
        <!ATTLIST adddatetimeinput structure CDATA #REQUIRED>

    <!ELEMENT editview (editdateinput,edittimeinput,edittextarea,editdefaultinput,editdatetimeinput)>
    <!ATTLIST editview structure CDATA #REQUIRED>

        <!ELEMENT editdateinput EMPTY>
        <!ATTLIST editdateinput structure CDATA #REQUIRED>

        <!ELEMENT edittimeinput EMPTY>
        <!ATTLIST edittimeinput structure CDATA #REQUIRED>

        <!ELEMENT edittextarea EMPTY>
        <!ATTLIST edittextarea structure CDATA #REQUIRED>

        <!ELEMENT editdefaultinput EMPTY>
        <!ATTLIST editdefaultinput structure CDATA #REQUIRED>

        <!ELEMENT editdatetimeinput EMPTY>
        <!ATTLIST editdatetimeinput structure CDATA #REQUIRED>

=== danteay/CorePHP/setup/themes/NewDefault/configTheme.xml
<!DOCTYPE components SYSTEM "themedtd.dtd">

<!--
@Theme Name: Default
@Athor: Dante - dante.aguilar41@gmail.com
-->

<components>

	<directives>
		<name>Default</name>
		<findfolder>NewDefault</findfolder>

		<makedirs>
			<dir>actionsjs</dir>
		</makedirs>
	</directives>

	<general>
		<navigation structure="viewComponents/navegacion.html" />

        <plugins>

            <dateplugin css="" js="">
                <activation actcode="viewComponents/dateplugin/actcode.html"/>
            </dateplugin>

            <timeplugin css="" js="">
                <activation actcode="viewComponents/timeplugin/actcode.html"/>
            </timeplugin>

			<datetimeplugin css="viewComponents/datetimeplugin/css.html" js="viewComponents/datetimeplugin/js.html">
				<activation actcode="viewComponents/datetimeplugin/actcode.html"/>
			</datetimeplugin>

        </plugins>
	</general>

	<views>
		<indexview structure="views/index.html" />

		<homeview structure="views/home.html">

			<listNavigation structure="viewComponents/homeListNavigation.html" />

		</homeview>

		<reportview structure="views/reporte.html">

			<editbutton structure="viewComponents/reportEditButton.html" header="viewComponents/reportEditHeader.html" />

		</reportview>

		<addview structure="views/agregar.html">

			<adddateinput structure="viewComponents/addDefaultInput.html" />
			<addtimeinput structure="viewComponents/addDefaultInput.html" />
			<addtextarea structure="viewComponents/addTextarea.html" />
			<adddefaultinput structure="viewComponents/addDefaultInput.html" />
			<adddatetimeinput structure="viewComponents/addDefaultInput.html" />

		</addview>

		<editview structure="views/editar.html">

			<editdateinput structure="viewComponents/editDefaultInput.html" />
			<edittimeinput structure="viewComponents/editDefaultInput.html" />
			<edittextarea structure="viewComponents/editTextarea.html" />
			<editdefaultinput structure="viewComponents/editDefaultInput.html" />
			<editdatetimeinput structure="viewComponents/editDefaultInput.html" />

		</editview>
	</views>

</components>
